# Generated by Django 3.0.3 on 2020-04-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stutable',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.AlterField(
            model_name='stutable',
            name='head_img',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='头像'),
        ),
    ]
