# Generated by Django 3.0.3 on 2020-04-14 07:20

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20200413_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stutable',
            name='head_img',
            field=stdimage.models.StdImageField(null=True, upload_to='img/', verbose_name='头像'),
        ),
    ]
