# Generated by Django 3.0.3 on 2020-04-15 03:12

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_auto_20200415_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stutable',
            name='head_img',
            field=stdimage.models.StdImageField(blank=True, default=1, upload_to='path/to/', verbose_name='url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stutable',
            name='password_hash',
            field=models.CharField(blank=True, default=2, max_length=128, verbose_name='密码'),
            preserve_default=False,
        ),
    ]
