# Generated by Django 3.0.3 on 2020-04-15 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_auto_20200415_1112'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stutable',
            table='user_info',
        ),
    ]
